### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by doelgonzo** [dai-shi/react-hooks-worker#33]
We're using this for a project in TypeScript, and noticed there are no permissible return types for the `result` object, as it is set to `unknown` 
https://github.com/dai-shi/react-hooks-worker/blob/cf995a95f30d12ed752e3c221a61a790eae9f165/src/useWorker.ts#L9

Could we make a change here to allow devs to be more specific?
For example
```
type State<T extends unknown> = {
  result?: T 
  error?: 'error' | 'messageerror'
}

const initialState: State<any> = {}
```

Then we can define `useWorker` as follows:
```
export function useWorker<T, K>(
  createWorker: () => Worker,
  input: T
): State<K> {
  const [state, setState] = useState<State<K>>(initialState)
  ...
```

and usages can be like:
```
 const { result, error } = useWorker<number, number>(createWorker, count);
```
or
```
 const { result, error } = useWorker<SimpleType, ComplexType>(createWorker, simpleInput);
// result will be of type ComplexType
```

This would allow us to know the type of the result object more clearly.

Thoughts are welcome

**Comment by dai-shi** [comment]
Nice catch! absolutely!

**Comment by doelgonzo** [comment]
@dai-shi Sorry to be a bother, but can you provide an estimate for a patch bump on the package so we can get the latest definitions?

**Comment by doelgonzo** [comment]
Thanks!
