### ISSUE TITLE
Error when using async function and exposeWorker

### ISSUE THREAD

**Issue by doelgonzo** [dai-shi/react-hooks-worker#35]
I am currently getting an error when trying to use the async pattern in a worker to be exposed, and I am not sure I understand why it happens. Does the library not support an async function? I thought that was included under returning a promise. Maybe I'm misusing this? Please advise.

The error is below:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Symbol(Symbol.asyncIterator)')
    at self.onmessage (exposeWorker.ts:23)
```

This snippet is an example of the such.
```
...
import { exposeWorker } from 'react-hooks-worker'
...
...
const fetchAndTransform = async (someUrl) => {
  const response = await fetch(someUrl)
  const result = someExpensiveTransformFunction(response)

  return result
}

exposeWorker(fetchAndTransform)
```

**Comment by dai-shi** [comment]
Surely, it should support async functions.
I don't see anything wrong in your snippet.
Can you make a small reproduction?

But anyway, that error messages reveals a potential bug.
I also noticed that there are no simple async examples in the `examples` folder.
Let me work on them.

**Comment by dai-shi** [comment]
I added a simple async example in #36.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-hooks-worker/v/1.0.3

**Comment by doelgonzo** [comment]
Thanks! The update fixed my issue
