### ISSUE TITLE
Dependency array

### ISSUE THREAD

**Issue by rssfrncsrenishaw** [dai-shi/react-hooks-worker#4]
Hi,

Just giving this library a try and wondering if there is a way to provide a dependency array like useEffect?

**Comment by dai-shi** [comment]
https://github.com/dai-shi/react-hooks-worker/blob/7efdf4f27a63dc9af64cdf3a23e85f3e33e6f6ae/src/index.js#L29

The second argument is passed into deps. So, you can control with it.
This also means users have to `useMemo` to avoid unintentional invocations.

I'm interested in your use case.

**Comment by rssfrncsrenishaw** [comment]
Ah of course thanks.

My use case for web-workers in general? Or using this library?

I'm using workers to transform between data types with a really large dataset. I'm finding hooks are a really nice way to use them. I was using workerize beforehand (which is great, but this reduces the component code further).

**Comment by dai-shi** [comment]
Thanks. Have you tried comlink before?

Also, I updated this library since then. If you have a chance, please give it a try.

Closing this issue. You can continue posting feedback after that, or create a new issue.
