### ISSUE TITLE
How about sharedworkers?

### ISSUE THREAD

**Issue by kamtoeddy** [dai-shi/react-hooks-worker#48]
Please does this module support shared workers in reactjs?
if yes, please demo or link for demo. Also, need help with shared workers for react app. Thanks

**Comment by dai-shi** [comment]
I never used SharedWorkers, but SharedWorker and WebWorkder seem very different. I don't think it works, because the API is different and useWorker hook is designed to work with React lifecycle.

You might want to look for general React resources for help with shared workers.

**Comment by kamtoeddy** [comment]
Ok thanks
