### ISSUE TITLE
Unable to call external modules inside a workerized function

### ISSUE THREAD

**Issue by dangdennis** [dai-shi/react-hooks-worker#6]
## Issue

I realize that you can’t inline `useWorker(function)` if  `function` uses imported modules and isn’t written in its own file. Basically, having side-effects in your functions. Webpack doesn’t seem to compile the dependencies as-is.

## Error
Example error: js_cookie__WEBPACK_IMPORTED_MODULE_7___default

js-cookie being the npm module.

## Solution
1. Add documentation to warn users that you must move web worker functions into their own files with their own imports.
2. Maybe even explicitly throw Errors

**Comment by dai-shi** [comment]
Thanks for bringing this up.

> Maybe even explicitly throw Errors

I thought about this, but this would require a protocol to talk with worker, and I had a bit hesitation.
This not for UX, but for DX. Maybe it's worth to re-consider it.

> Add documentation to warn users

This should be good for an immediate solution.

For the long term, I'd like to come up with better solutions to really solve the issue.
Probably I'd learn how Percel bundles code for workers at the beginning. (and how about webpack?)

I also want to learn use cases. How do people use workers with hooks? (and does it have to be a hook?)
@dangdennis Do you have any specific use case in your mind?

**Comment by dangdennis** [comment]
Surma from google told me that he basically uses web workers whenever he can: web workers do all explicit data work, thus the main thread can do only UI work.

In my case, say I’m filtering and mapping large arrays, etc, I’ll wrap all that in useWorker

**Comment by dangdennis** [comment]
I left a comment in the PR.

Comlink and workerize both have a webpack loader libraries.
