### ISSUE TITLE
createWorker with a string is just a glorified eval

### ISSUE THREAD

**Issue by pocesar** [dai-shi/react-hooks-worker#8]
Put a caveat on the README warning about passing inline stuff or strings into the hook so you don't shoot yourself in the foot with XSS

**Comment by dai-shi** [comment]
Reasonable point. Thanks for raising this up. I'll update the README later.

(On the other hand, I'd like to seek possibilities to avoid API with bare strings.)

**Comment by pocesar** [comment]
if you decide to leave that in, would be a good thing to call `URL.revokeObjectURL` on an `useEffect()` cleanup, but keeping track if the consumer used an string or not might be cumbersome

**Comment by dai-shi** [comment]
Would you review #9?

**Comment by pocesar** [comment]
LGTM 👍

**Comment by dai-shi** [comment]
Thanks!
